apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gophers-forumcleaner.name" . }}-token"
type: Opaque
data:
  token: {{ .Values.botToken | required ".Values.botToken is required." | b64enc }}